server:
  #port: 7071
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: bc-customer-service
  
  datasource:
    url: jdbc:postgresql://ep-long-dew-ac1nbm3d-pooler.sa-east-1.aws.neon.tech/bc-customer?user=bc-customer_owner&password=npg_NrwQXIeWT1d8&sslmode=require
    username: bc-customer_owner
    password: npg_NrwQXIeWT1d8
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:7070/eureka
      defaultZone: ${EUREKA_URI:http://localhost:7070/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
