server:
  #port: 7073
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: bc-salesrules-service
  
  datasource:
    url: jdbc:postgresql://ep-icy-butterfly-a8j61zye-pooler.eastus2.azure.neon.tech/bc-salesrules?user=bc-salesrules_owner&password=npg_Ssw1H4fmqPeL&sslmode=require
    username: bc-salesrules_owner
    password: npg_Ssw1H4fmqPeL
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:7070/eureka
      defaultZone: ${EUREKA_URI:http://localhost:7070/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
