server:
  port: 2999

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:2020/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: bc-sales-service
              uri: lb://bc-sales-service
              predicates:
                - Path=/venta/**, /detalleventa/**
              filters:
                - AuthFilter
          
            - id: bc-salesrules-service
              uri: lb://bc-salesrules-service
              predicates:
                - Path=/formapago/**, /tipoventa/**
              filters:
                - AuthFilter
    
            - id: ms-cliente-service
              uri: lb://ms-cliente-service
              predicates:
                - Path=/cliente/**
              #filters:
                #- AuthFilter
    
            - id: ms-producto-service
              uri: lb://ms-producto-service
              predicates:
                - Path=/producto/**, /marca/**, /genero/**, /color/**
              #filters:
                #- AuthFilter
              
            - id: ms-auth-service
              uri: lb://ms-auth-service
              predicates:
                - Path=/auth/**
          

          globalcors:
            '[/**]':
              allowedOrigins: "http://localhost:4200"
              allowedMethods: "*"
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 3600
